"""Load-balancing-specific pricing adapters."""

from __future__ import annotations

import warnings
from typing import Any

import numpy as np

from asunder.base.column_generation.pricing import (
    build_dual_weight_matrix,
    compute_reduced_cost,
)
from asunder.load_balancing.algorithms.qmetis import (
    QMETISApproximationWarning,
    run_qmetis,
)
from asunder.load_balancing.utils.balance import (
    epsilon_for_upper_bound,
    resolve_balance_bounds,
)


def _balanced_fallback_partition(n_nodes: int, K: int) -> np.ndarray:
    """Construct a deterministic near-equal partition.

    Parameters
    ----------
    n_nodes : int
        Number of nodes to assign.
    K : int
        Number of requested parts.

    Returns
    -------
    numpy.ndarray
        Binary co-association matrix produced by round-robin node assignment.

    Raises
    ------
    ValueError
        If ``K`` is not between one and ``n_nodes``.
    """

    if K < 1 or K > n_nodes:
        raise ValueError("K must be between 1 and the number of nodes.")
    labels = np.arange(n_nodes, dtype=int) % K
    return np.equal.outer(labels, labels).astype(int)


def _warn_about_ignored_internal_mass() -> None:
    """Warn that contracted diagonal mass is omitted from QMETIS search."""

    warnings.warn(
        "QMETIS pricing drops nonzero adjacency diagonal values, including "
        "contracted internal-edge mass. Candidate generation is approximate; "
        "the returned reduced cost is still evaluated exactly.",
        QMETISApproximationWarning,
        stacklevel=3,
    )


def qmetis_pricing_subproblem(
    A: np.ndarray,
    a: np.ndarray,
    m: float,
    duals: dict[str, Any],
    *,
    K: int,
    R: int,
    R_bounds: tuple[int | None, int | None] | None = None,
    verbose: int | bool = False,
    seed: int | None = None,
    **_: Any,
) -> tuple[float, np.ndarray]:
    """Generate and exactly score a pricing candidate with QMETIS.

    QMETIS receives a nonnegative approximation of the dual-adjusted pricing
    matrix. Its imbalance tolerance is derived only as a search envelope from
    the master's permitted upper community-size bound. The candidate's
    reduced cost is always recomputed with the original floating-point data.

    Parameters
    ----------
    A : numpy.ndarray
        Original or contracted adjacency matrix used by the exact pricing
        objective.
    a : numpy.ndarray
        Degree/strength vector associated with ``A``.
    m : float
        Total directed graph weight used by Asunder's modularity formula.
    duals : dict[str, Any]
        Scalar, node-level, and pair-level master dual values.
    K : int
        Requested number of load-balanced communities.
    R : int
        Width of the permitted community-size range.
    R_bounds : tuple[int or None, int or None] or None
        Optional explicit lower and upper community-size bounds.
    verbose : int or bool, default=False
        Emit pricing diagnostics when enabled.
    seed : int or None
        QMETIS random seed.
    **_ : Any
        Ignored compatibility keywords from generic pricing dispatch.

    Returns
    -------
    reduced_cost : float
        Exact, unquantized reduced cost of the generated candidate.
    partition : numpy.ndarray
        Binary co-association matrix generated by QMETIS or the deterministic
        edgeless fallback.

    Warns
    -----
    QMETISApproximationWarning
        If ``A`` has a nonzero diagonal. Contraction-generated internal mass
        is excluded from QMETIS candidate generation because its self-loop
        semantics are unsupported, but remains in exact rescoring.

    Notes
    -----
    Negative dual-adjusted edges are clipped to zero only for candidate
    generation. The clipping, integer quantization, and diagonal removal do
    not alter the exact reduced-cost calculation.
    """

    adjacency = np.asarray(A, dtype=np.float64)
    if adjacency.ndim != 2 or adjacency.shape[0] != adjacency.shape[1]:
        raise ValueError("A must be a square matrix.")

    _, R_max = resolve_balance_bounds(adjacency.shape[0], K, R, R_bounds)
    epsilon = epsilon_for_upper_bound(adjacency.shape[0], K, R_max)
    has_ignored_internal_mass = bool(np.any(np.diag(adjacency) != 0))

    dual_weight, _ = build_dual_weight_matrix(adjacency, duals)
    pricing_weights = adjacency - float(m) * dual_weight
    qmetis_weights = np.maximum(pricing_weights, 0.0)
    np.fill_diagonal(qmetis_weights, 0.0)

    if np.any(qmetis_weights > 0):
        if has_ignored_internal_mass:
            _warn_about_ignored_internal_mass()
        z_sol, _native_metric = run_qmetis(
            qmetis_weights,
            K,
            balance_epsilon=epsilon,
            seed=seed,
        )
    else:
        # A fully clipped pricing graph has no meaningful modularity
        # direction. Reuse positive original topology when available, and
        # otherwise return a deterministic balanced candidate. Either path is
        # evaluated below with the exact floating-point reduced cost.
        fallback_weights = np.maximum(
            0.5 * (adjacency + adjacency.T),
            0.0,
        )
        np.fill_diagonal(fallback_weights, 0.0)
        if np.any(fallback_weights > 0):
            if has_ignored_internal_mass:
                _warn_about_ignored_internal_mass()
            z_sol, _native_metric = run_qmetis(
                fallback_weights,
                K,
                balance_epsilon=epsilon,
                seed=seed,
            )
        else:
            z_sol = _balanced_fallback_partition(adjacency.shape[0], K)
    reduced_cost = compute_reduced_cost(
        adjacency,
        np.asarray(a),
        float(m),
        z_sol,
        duals,
    )

    if verbose not in (-1, False, 0):
        print(
            f"[QMETIS pricing] epsilon={epsilon:.6g}, "
            f"reduced_cost={reduced_cost:.8g}, "
            f"ignored_diagonal={has_ignored_internal_mass}"
        )

    return reduced_cost, z_sol
